### ISSUE TITLE
Save uploaded image to a file

### ISSUE THREAD

**Issue by Better-Boy** [nerdy-harry/bootstrap-imageupload#1]
I'm a beginner in javascript and your work is excellent.
What should I do in order to save the uploaded image to file?

**Comment by nerdy-harry** [comment]
Thanks for the appreciation. Do give a star to my repository if you liked my work.
In order to save the uploaded image to file you need to use HTML5 FileReader API.
Refer this [blog link](https://blog.teamtreehouse.com/reading-files-using-the-html5-filereader-api) for a nice tutorial about it. You can also [refer this link](https://stackoverflow.com/questions/31850732/save-a-file-image-to-localstorage-html) for the complete implementation.
